more info

diff --git a/sphp b/sphp
--- a/sphp
+++ b/sphp
@@ -21,13 +21,26 @@ fi
 currentversion="`php -r \"error_reporting(0); echo str_replace('.', '', substr(phpversion(), 0, 3));\"`"
 newversion="$1"
 
-shortOld="`php -r \"error_reporting(0); echo substr(phpversion(), 0, 1);\"`"
-shortNew="`php -r \"error_reporting(0); echo substr('$1', 0, 1);\"`"
+majorOld=${currentversion:0:1}
+majorNew=${newversion:0:1}
+minorNew=${newversion:1:1}
 
 brew list php$newversion 2> /dev/null > /dev/null
 
 if [ $? -eq 0 ]; then
 	echo "PHP version $newversion found"
+
+	# Check if new version is already the current version.
+	if [ "${newversion}" == "${currentversion}" ]; then
+	    echo -n "PHP version ${newversion} is already being used. Continue by reloading? (y/n) "
+	    while true; do
+	        read -n 1 yn
+	        case $yn in
+	            [Yy]* ) echo && break;;
+	            [Nn]* ) echo && exit 1;;
+	        esac
+	    done
+	fi
 
 	echo "Unlinking old binaries..."
 	brew unlink php$currentversion 2> /dev/null > /dev/null
@@ -40,8 +53,8 @@ if [ $? -eq 0 ]; then
 
 	echo "Fixing LoadModule..."
 	apacheConf=`httpd -V | grep -i server_config_file | cut -d '"' -f 2`
-	sudo sed -i -e "/LoadModule php${shortOld}_module/s/^#*/#/" $apacheConf
-	sudo sed -i -e "/LoadModule php${shortNew}_module \/usr\/local\/opt\/php${newversion}/s/^#//" $apacheConf
+	sudo sed -i -e "/LoadModule php${majorOld}_module/s/^#*/#/" $apacheConf
+	sudo sed -i -e "/LoadModule php${majorNew}_module \/usr\/local\/opt\/php${newversion}/s/^#//" $apacheConf
 
 	echo "Updating version file..."
 
@@ -64,7 +77,11 @@ if [ $? -eq 0 ]; then
 	fi
 
 	echo "Done."
+
+	# Show PHP CLI version for verification.
+	echo && php -v
 else
-	echo "PHP version $newversion was not found."
+	echo "PHP version $majorNew.$minorNew was not found."
+	echo "Try \`brew install php${newversion}\` first."
 	exit 1
 fi
